# -*- mode: python ; coding: utf-8 -*-

import sys
sys.path.insert(0, 'src/python')
from rtt_tool import __version__
import os

a = Analysis(
    ['src/scripts/main.py'],
    pathex=['src/python'],
    binaries=[],
    datas=[('config/i18n', 'config/i18n')],
    hiddenimports=[
        'rtt_tool.i18n', 'rtt_tool.i18n.translations', 'rtt_tool.i18n.loader',
        'rtt_tool.backend', 'rtt_tool.backend.base', 'rtt_tool.backend.jlink_backend',
        'rtt_tool.backend.pyocd_backend', 'rtt_tool.backend.manager',
        'rtt_tool.processors', 'rtt_tool.processors.base', 'rtt_tool.processors.log_processor',
        'rtt_tool.processors.waveform_processor', 'rtt_tool.processors.variable_monitor',
        'rtt_tool.plugins', 'rtt_tool.plugins.plugin_base', 'rtt_tool.plugins.plugin_manager',
        'rtt_tool.utils.data_export_service', 'rtt_tool.utils.data_replay_service',
        'rtt_tool.runtime', 'rtt_tool.runtime.path_config',
        'rtt_tool.runtime.dependency_manifest', 'rtt_tool.runtime.dependency_checker',
        'rtt_tool.runtime.runtime_guard', 'rtt_tool.runtime.setup_wizard',
        'rtt_tool.runtime.pyocd_target_index',
        'pyqtgraph', 'pyqtgraph.graphicsItems', 'pyqtgraph.graphicsItems.PlotItem',
        'pyqtgraph.graphicsItems.PlotCurveItem', 'pyqtgraph.graphicsItems.ViewBox',
        'pyqtgraph.graphicsItems.AxisItem', 'pyqtgraph.graphicsItems.GridItem',
        'pyqtgraph.graphicsItems.GraphicsLayout', 'pyqtgraph.graphicsItems.LegendItem',
        'pyqtgraph.graphicsItems.ScatterPlotItem', 'pyqtgraph.graphicsItems.BarGraphItem',
        'pyqtgraph.widgets', 'pyqtgraph.widgets.PlotWidget', 'pyqtgraph.widgets.GraphicsView',
        'pyqtgraph.exporters', 'pyqtgraph.exporters.ImageExporter',
        'pyqtgraph.exporters.SVGExporter', 'pyqtgraph.exporters.CSVExporter',
        'pyqtgraph.exporters.MatplotlibExporter',
        'numpy', 'numpy.core', 'numpy._core', 'numpy.fft', 'numpy.linalg',
        'numpy.random', 'numpy.ma', 'numpy.lib',
        'xml', 'xml.etree', 'xml.etree.ElementTree',
        'xml.parsers', 'xml.parsers.expat',
        'html', 'html.parser',
        'pdb', 'cmd', 'bdb', 'linecache', 'code', 'codeop',
        'pydoc', 'pydoc_data', 'pydoc_data.topics',
        'socket', 'ssl', 'http', 'http.client', 'http.server',
        'urllib', 'urllib.parse', 'urllib.request', 'urllib.error',
        'email', 'email.mime', 'email.mime.text', 'email.parser',
        'csv', 'queue', 'concurrent', 'concurrent.futures',
        'typing', 'dataclasses', 'importlib', 'importlib.util',
        'importlib.abc', 'importlib.machinery',
        'struct', 'binascii', 'tempfile', 'shutil', 'glob',
        'logging', 'logging.config', 'logging.handlers',
        'hashlib', 'hmac', 'secrets', 'base64',
        'json', 'json.decoder', 'json.encoder',
        'zipfile', 'tarfile', 'gzip', 'bz2', 'lzma',
        'sqlite3', 'sqlite3.dbapi2',
        'xmlrpc', 'xmlrpc.client', 'xmlrpc.server',
        'multiprocessing', 'multiprocessing.queues',
        'threading', 'subprocess', 'signal',
        'inspect', 'dis', 'tokenize', 'ast', 'compileall',
        'unittest', 'unittest.mock',
        'copy', 'copyreg', 'weakref', 'types', 'functools',
        'itertools', 'operator', 'contextlib', 'abc',
        'pathlib', 'io', 'mmap', 'select', 'msvcrt',
        'ctypes', 'ctypes.util', 'ctypes.wintypes',
        'configparser', 'argparse', 'getopt',
        're', 'sre_compile', 'sre_parse', 'sre_constants',
        'decimal', 'fractions', 'numbers', 'math', 'cmath',
        'random', 'statistics', 'datetime', 'calendar',
        'zoneinfo', 'gettext', 'locale',
        'platform', 'sysconfig', 'site',
        'netrc', 'ftplib', 'smtplib', 'telnetlib',
        'plistlib', 'tomllib', 'token',
        'py_compile', 'symbol', 'symtable',
        'traceback', 'warnings', 'faulthandler',
        'atexit', 'fnmatch', 'stat',
        'pprint', 'reprlib', 'textwrap',
        'difflib', 'heapq', 'bisect',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=['src/scripts/runtime_hook_usb.py'],
    excludes=[
        'numba', 'llvmlite', 'scipy', 'pandas', 'matplotlib',
        'PIL', 'Pillow', 'tkinter', 'tcl', 'tk',
        'IPython', 'jupyter', 'notebook',
        'sphinx', 'docutils', 'pytest',
        'cv2', 'opencv',
        'sqlalchemy', 'django', 'flask',
        'zmq', 'tornado',
        'lxml', 'html5lib', 'beautifulsoup4', 'bs4',
        'pyarrow', 'h5py',
        'sympy', 'networkx',
        'cmsis_pack_manager',
        'usb', 'usb1', 'pyocd', 'hid', 'hidapi',
    ],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name=f'RTT-Assistant v{__version__}',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='resources/icon.ico',
)
