c = c.replace('f"<h3>检查更新</h3>"', 'f"<h3>{i18n(\'dialog.check_update\')}</h3>"')
c = c.replace('QLabel("正在检查更新…")', 'QLabel(i18n("error.checking_update"))')
c = c.replace('["来源", "最新版本", "状态", "操作"]', '[i18n("header.source"), i18n("header.latest_version"), i18n("header.status"), i18n("header.action")]')
c = c.replace('self._status_label.setText("正在检查更新…")', 'self._status_label.setText(i18n("error.checking_update"))')
c = c.replace('QTableWidgetItem("检查失败")', 'QTableWidgetItem(i18n("error.check_failed"))')
c = c.replace('QTableWidgetItem("请检查网络连接后重试")', 'QTableWidgetItem(i18n("error.check_network"))')
c = c.replace('QTableWidgetItem("有新版本 ✓")', 'QTableWidgetItem(i18n("header.has_new_version") + " ✓")')
c = c.replace('QTableWidgetItem("已是最新")', 'QTableWidgetItem(i18n("header.is_latest"))')
c = c.replace('QPushButton("复制链接")', 'QPushButton(i18n("btn.copy_link"))')
c = c.replace('QPushButton("打开页面")', 'QPushButton(i18n("btn.open_page"))')
c = c.replace('"点击 Assets 选择文件，使用迅雷下载"', 'i18n("tooltip.github_assets")')
c = c.replace('"点击 下载 选择文件下载"', 'i18n("tooltip.gitee_download")')
c = c.replace('QMessageBox.information(self, "链接已复制",', 'QMessageBox.information(self, i18n("dialog.link_copied"),')
c = c.replace('f\'<p style="color:#888;">当前版本: v{self._current_version}</p>\'', '\'<p style="color:#888;">\' + i18n(\'label.current_version\') + f\' v{self._current_version}</p>\'')
c = c.replace('f\'<p style="color:#00AA00; font-weight:bold;">\'\n                f\'发现新版本！当前: v{self._current_version}</p>\'', '\'<p style="color:#00AA00; font-weight:bold;">\' + i18n(\'label.new_version_found\') + f\' v{self._current_version}</p>\'')
c = c.replace('f\'<p style="color:#888;">当前版本: v{self._current_version}（已是最新）</p>\'', '\'<p style="color:#888;">\' + i18n(\'label.current_version_latest\') + f\' v{self._current_version}</p>\'')
c = c.replace('f"{r[\'source\']}: {f[\'name\']}\\n点击复制下载链接"', 'f"{r[\'source\']}: {f[\'name\']}\\n" + i18n("tooltip.click_copy_link")')
c = c.replace('f"下载链接已复制到剪贴板{hint}\\n\\n{url}"', 'i18n("error.link_copied_to_clipboard").format(hint, url)')
c = c.replace('            hint = "（推荐使用迅雷下载）"', '            hint = i18n("error.recommend_thunder")')
